const express = require('express');
const morgan = require('morgan');
const cors = require('cors');

const server = express();

server.use(express.json());
server.use(cors());
server.use(morgan('dev'));

const roomRoutes = require('./controllers/rooms');
const userRoutes = require('./controllers/user');
server.use('/rooms', roomRoutes);
server.use('/user', userRoutes);

server.get('/', (req, res) => {
	res.status(200).send({ message: 'Hello world!' });
});

//RETURN score info for specific quiz
//LEADERBOARD PAGE
//app.get('/quiz/:id/score', (req, res) => {});

//CREATE A USER RECORD
//ID MATCHES THE ONE GENERATED BY FIREBASE
//id,username,avatar-url
//app.post('/user', (req, res) => {});

//CREATE ROOM
//room-id,room-name,private/public
// app.post('/rooms', (req, res) => {
// 	//
// });

//CREATE QUIZ
// //

//UPDATE QUIZ -> add user answers/scores
//app.patch('/quiz/:quizid', (req, res) => {});

module.exports = server;
